EduMart/Controllers/MentorsController.cs
using EduMart.Data;
using EduMart.Data.Services;
using EduMart.Data.Static;
using EduMart.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EduMart.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class MentorsController : Controller
    {
        private readonly IMentorsService _service;

        public MentorsController(IMentorsService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allMentors = await _service.GetAllAsync();
            return View(allMentors);
        }

        // Get Mentors/ Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfilePictureURL, FullName, About")] Mentors mentor)
        {
            if (!ModelState.IsValid)
            {
                // Log the model state errors
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Console.WriteLine(error.ErrorMessage);
                    }
                }
                return View(mentor);
            }
            await _service.AddAsync(mentor);
            return RedirectToAction(nameof(Index));
        }

        // Get Mentors/ Details/ 1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var mentorDetails = await _service.GetByIdAsync(id);
            if(mentorDetails == null)
            {
                return View("NotFound");
            }
            return View(mentorDetails);

        }

        //Get: Mentor/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var mentorDetails = await _service.GetByIdAsync(id);
            if (mentorDetails == null)
            {
                return View("NotFound");
            }
            return View(mentorDetails);
        }

        // Get: Mentor Update
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, ProfilePictureURL, FullName, About")] Mentors mentor)
        {
            if (id != mentor.Id)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View(mentor);
            }

            try
            {
                await _service.UpdateAsync(id, mentor);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await MentorExists(mentor.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> MentorExists(int id)
        {
            var mentor = await _service.GetByIdAsync(id);
            return mentor != null;
        }

        //Get: Mentor/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var mentorDetails = await _service.GetByIdAsync(id);
            if (mentorDetails == null)
            {
                return View("NotFound");
            }
            return View(mentorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mentorDetails = await _service.GetByIdAsync(id);
            if (mentorDetails == null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }




    }
}

EduMart/Controllers/OrdersController.cs
using EduMart.Data.Cart;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using EduMart.Data.Services;
using EduMart.Data.ViewModels;
using System.Security.Claims;

namespace EduMart.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly ShoppingCart _shoppingCart;
        private readonly ISkillsService _skillService;
        private readonly IOrdersService _ordersService;

        public OrdersController(ISkillsService skillService ,ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _skillService = skillService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
         {
             string userId = User.FindFirstValue(ClaimTypes.NameIdentifier); ;
             string userRole = User.FindFirstValue(ClaimTypes.Role);

             var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
             return View(orders);
         }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _skillService.GetSkillByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _skillService.GetSkillByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress );
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }

        public IActionResult Payment()
        {
            var totalAmount = _shoppingCart.GetShoppingCartTotal();
            ViewData["TotalAmount"] = totalAmount;
            return View();
        }
    }
}

EduMart/Controllers/PlatformsController.cs
using EduMart.Data;
using EduMart.Data.Services;
using EduMart.Data.Static;
using EduMart.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EduMart.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class PlatformsController : Controller
    {
        private readonly IPlatformService _service;
        public PlatformsController(IPlatformService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task <IActionResult> Index()
        {
             var allPlatforms = await _service.GetAllAsync();
            return View(allPlatforms);
        }

        // Get SkillOrganizers/ Details /1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var platformDetails = await _service.GetByIdAsync(id);
            if (platformDetails == null)
            {
                return View("NotFound");
            }
            return View(platformDetails);
        }

        // Get Platforms/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("PlatformLogo, PlatformName, Description")] Platforms platform)
        {
            if (!ModelState.IsValid)
            {
                // Log the model state errors
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Console.WriteLine(error.ErrorMessage);
                    }
                }
                return View(platform);
            }
            await _service.AddAsync(platform);
            return RedirectToAction(nameof(Index));
        }

        //Get: Skill Organizers/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var platformsDetails = await _service.GetByIdAsync(id);
            if (platformsDetails == null)
            {
                return View("NotFound");
            }
            return View(platformsDetails);
        }

        // Get: Platform Update
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, PlatformLogo, PlatformName, Description")] Platforms platforms)
        {
            if (id != platforms.Id)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View(platforms);
            }

            try
            {
                await _service.UpdateAsync(id, platforms);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await PlatformsExists(platforms.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> PlatformsExists(int id)
        {
            var platforms = await _service.GetByIdAsync(id);
            return platforms != null;
        }

        //Get: PLatform/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var platformDetails = await _service.GetByIdAsync(id);
            if (platformDetails == null)
            {
                return View("NotFound");
            }
            return View(platformDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var platformDetails = await _service.GetByIdAsync(id);
            if (platformDetails == null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

EduMart/Controllers/SkillsController.cs
using EduMart.Data.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using EduMart.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using EduMart.Data.Static;

namespace EduMart.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class SkillsController : Controller
    {
        private readonly ISkillsService _service;

        public SkillsController(ISkillsService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allSkills = await _service.GetAllAsync(n => n.Platforms);
            return View(allSkills);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allSkills = await _service.GetAllAsync(n => n.Platforms);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResultNew = allSkills.Where(n =>
                    n.SkillName.Contains(searchString, StringComparison.CurrentCultureIgnoreCase) ||
                    n.SkillDescription.Contains(searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filteredResultNew);
            }

            return View("Index", allSkills);
        }


        // Get: Skills/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var skillDetails = await _service.GetSkillByIdAsync(id);
            if (skillDetails == null)
            {
                return NotFound();
            }
            return View(skillDetails);
        }

        //GET: Skills/Create
        public async Task<IActionResult> Create()
        {
            var skillDropdownsData = await _service.GetNewSkillDropdownValuesAsync();

            ViewBag.Platforms = new SelectList(skillDropdownsData.platforms, "Id", "PlatformName");
            ViewBag.SkillOrganizers = new SelectList(skillDropdownsData.skillOrganizers, "Id", "FullName");
            ViewBag.Mentors = new SelectList(skillDropdownsData.mentors, "Id", "FullName");

            var model = new NewSkillsVM
            {
                StartDate = DateTime.Now,
                EndDate = DateTime.Now.AddDays(1)
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewSkillsVM skill)
        {
            if (!ModelState.IsValid)
            {
                var skillDropdownsData = await _service.GetNewSkillDropdownValuesAsync();

                ViewBag.Platforms = new SelectList(skillDropdownsData.platforms, "Id", "PlatformName");
                ViewBag.SkillOrganizers = new SelectList(skillDropdownsData.skillOrganizers, "Id", "FullName");
                ViewBag.Mentors = new SelectList(skillDropdownsData.mentors, "Id", "FullName");

                return View(skill);
            }

            await _service.AddNewSkillAsync(skill);
            return RedirectToAction(nameof(Index));
        }


        //GET: Skills/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var skillDetails = await _service.GetSkillByIdAsync(id);
            if (skillDetails == null)
            {
                return View("NotFound");
            }

            var response = new NewSkillsVM()
            {
                Id = skillDetails.Id,
                SkillName = skillDetails.SkillName,
                Description = skillDetails.SkillDescription,
                Price = skillDetails.Price,
                StartDate = skillDetails.StartDate,
                EndDate = skillDetails.EndDate,
                ImageURL = skillDetails.ImageURL,
                PlatformId = skillDetails.PlatformId,
                SkillCategory = skillDetails.SkillCategory,
                SkillOrganizerID = skillDetails.SkillOrganizerID,
                MentorIds = skillDetails.Mentors_Skills.Select(n => n.MentorID).ToList()
            };

            var skillDropdownsData = await _service.GetNewSkillDropdownValuesAsync();

            ViewBag.Platforms = new SelectList(skillDropdownsData.platforms, "Id", "PlatformName");
            ViewBag.SkillOrganizers = new SelectList(skillDropdownsData.skillOrganizers, "Id", "FullName");
            ViewBag.Mentors = new SelectList(skillDropdownsData.mentors, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewSkillsVM skill)
        {
            if(id != skill.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var skillDropdownsData = await _service.GetNewSkillDropdownValuesAsync();

                ViewBag.Platforms = new SelectList(skillDropdownsData.platforms, "Id", "PlatformName");
                ViewBag.SkillOrganizers = new SelectList(skillDropdownsData.skillOrganizers, "Id", "FullName");
                ViewBag.Mentors = new SelectList(skillDropdownsData.mentors, "Id", "FullName");

                return View(skill);
            }

            await _service.UpdateSkillAsync(skill);
            return RedirectToAction(nameof(Index));
        }
    }
}

EduMart/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">You've reached the end of the internet</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Skills" asp-action="Index">Home Page</a>
    </div>
</div>

EduMart/Views/Shared/_CreateItem.cshtml
@model string;

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>
}

EduMart/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;
@inject SignInManager<ApplicationUser> SignInManager;

@{
    var user = await UserManager.GetUserAsync(User);
    var fullName = user?.FullName ?? "User";
}

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-secondary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}
else
{

    @*User profile section*@
    <div class="dropdown">
        <button class="btn btn-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @fullName
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>

            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
            }
        </ul>
    </div>
    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}

EduMart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EduMart</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-primary border-bottom box-shadow mb-4">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Skills" asp-action="Index">
                    <i class="bi bi-shop"></i> <b>EduMart</b>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Skills" asp-action="Index"><i class="bi bi-journal-bookmark-fill"></i> Skills</a>
                        </li>

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin")){
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear-fill"></i> Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Platforms" asp-action="Index"><i class="bi bi-play-btn-fill"></i> Platforms</a>
                                    <a class="dropdown-item" asp-controller="SkillOrganizers" asp-action="Index"><i class="bi bi-person-workspace"></i> Agencies</a>
                                    <a class="dropdown-item" asp-controller="Mentors" asp-action="Index"><i class="bi bi-person-circle"></i> Mentors</a>
                                </div>
                            </li>
                        }

                        
                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Skills" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a skill..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>

                    <partial name="_Identity.cshtml" />
                   
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>